import { useEffect, useState } from "react";
import { ArrowRight, BookOpen, CalendarDays, Flame, Target, TrendingUp } from "lucide-react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Link } from "react-router-dom";
import { api, errorMessage } from "../services/api";
import type { DashboardData } from "../types";
import { Card, EmptyState, Loading, PageTitle, ProgressBar } from "../components/ui";

export default function InsightsPage() {
  const [data, setData] = useState<DashboardData | null>(null);
  const [error, setError] = useState("");
  useEffect(() => { void api.get<DashboardData>("/dashboard").then(({ data: value }) => setData(value)).catch((cause) => setError(errorMessage(cause))); }, []);
  if (!data && !error) return <Loading label="Gathering your learning insights" />;
  if (error || !data) return <div className="notice-error">{error}</div>;
  const allMinutes = data.weeklyActivity.reduce((sum, day) => sum + day.minutes, 0);
  const avg = data.weeklyActivity.filter((day) => day.minutes).length ? Math.round(allMinutes / data.weeklyActivity.filter((day) => day.minutes).length) : 0;
  const completedTopics = data.subjects.reduce((sum, subject) => sum + (subject.completedTopics ?? 0), 0);
  return <div><PageTitle eyebrow="NOTICE HOW FAR YOU’VE COME" title="Progress insights" description="Your learning is a journey. Here’s a little snapshot of yours." />
    <div className="insight-stat-grid"><Card><span className="insight-stat-icon insight-purple"><TrendingUp size={18} /></span><strong>{Math.floor(allMinutes / 60)}h {allMinutes % 60}m</strong><span>Focused this week</span></Card><Card><span className="insight-stat-icon insight-green"><BookOpen size={18} /></span><strong>{completedTopics}</strong><span>Topics completed</span></Card><Card><span className="insight-stat-icon insight-orange"><Flame size={18} /></span><strong>{data.user.studyStreak} days</strong><span>Current study streak</span></Card><Card><span className="insight-stat-icon insight-blue"><Target size={18} /></span><strong>{avg} min</strong><span>Average focus day</span></Card></div>
    <div className="insight-main-grid"><Card className="insight-chart-card"><div className="card-heading"><div><h2>Time you made for yourself</h2><p>Daily focus minutes · last 7 days</p></div><span className="insight-chart-total">{allMinutes} <small>min</small></span></div><div className="insight-chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data.weeklyActivity} margin={{ top: 12, right: 12, left: -18, bottom: 0 }}><defs><linearGradient id="insightsFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#38ad92" stopOpacity={0.18} /><stop offset="100%" stopColor="#38ad92" stopOpacity={0} /></linearGradient></defs><CartesianGrid vertical={false} stroke="#eef0f5" strokeDasharray="3 4" /><XAxis dataKey="day" axisLine={false} tickLine={false} tick={{ fontSize: 11, fill: "#9299a9" }} dy={10} /><YAxis axisLine={false} tickLine={false} tick={{ fontSize: 10, fill: "#9299a9" }} /><Tooltip formatter={(value) => [`${value} min`, "Focus time"]} contentStyle={{ border: "1px solid #eceaf6", borderRadius: 12, fontSize: 12 }} /><Area type="monotone" dataKey="minutes" stroke="#39a88f" strokeWidth={2.5} fill="url(#insightsFill)" /></AreaChart></ResponsiveContainer></div><p className="insight-encouragement">Every minute you spend learning is an investment in yourself.</p></Card><Card className="insight-exams"><div className="card-heading"><div><h2>On the horizon</h2><p>Upcoming exam dates</p></div><CalendarDays size={17} className="muted-icon" /></div>{data.subjects.filter((subject) => subject.examDate && new Date(subject.examDate) >= new Date()).length ? <div className="exam-list">{data.subjects.filter((subject) => subject.examDate && new Date(subject.examDate) >= new Date()).map((subject) => { const days = Math.ceil((new Date(subject.examDate!).getTime() - Date.now()) / 86400000); return <div className="exam-row" key={subject.id}><span className="exam-color-dot" style={{ background: subject.color }} /><div><strong>{subject.name}</strong><small>{new Date(subject.examDate!).toLocaleDateString("en", { month: "long", day: "numeric", year: "numeric" })}</small></div><span className="exam-days">{days === 0 ? "Today" : `${days}d`}</span></div>; })}</div> : <EmptyState title="Nothing around the corner" text="Add an exam date to a subject and it’ll appear here." />}</Card></div>
    <Card className="insight-subjects"><div className="card-heading"><div><h2>Your subjects, at a glance</h2><p>Understanding grows one topic at a time</p></div><Link className="text-link" to="/subjects">Go to subjects <ArrowRight size={14} /></Link></div>{data.subjects.length ? <div className="insight-subject-list">{data.subjects.map((subject) => <div key={subject.id} className="insight-subject-row"><span className="subject-emoji" style={{ background: `${subject.color}17` }}>{subject.icon}</span><span className="insight-subject-name"><strong>{subject.name}</strong><small>{subject.completedTopics ?? 0}/{subject.topicCount ?? 0} topics completed</small></span><div className="insight-subject-progress"><ProgressBar value={subject.progress ?? 0} color={subject.color} /></div><strong className="insight-subject-percent">{subject.progress ?? 0}%</strong></div>)}</div> : <EmptyState title="Your insights start with a subject" text="Add subjects and topics to follow your progress over time." action={<Link className="small-text-link" to="/subjects">Add a subject <ArrowRight size={13} /></Link>} />}</Card>
  </div>;
}
